# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tperes <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/27 14:51:54 by tperes            #+#    #+#              #
#    Updated: 2022/04/08 23:42:05 by tperes           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SRC_DIR = ./

SRC = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putlen_fd.c ft_putnbr_fd.c ft_printf.c ft_printf_utils.c

BONUS = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstadd_back.c ft_lstlast.c ft_lstdelone.c ft_lstclear.c

OBJS	=  ${SRC:.c=.o}

BONUSES = ${BONUS:.c=.o}

CC 	= cc

CFLAGS	= -Wall -Wextra -Werror

INCLUDE	= includes

all: ${NAME}

bonus: ${OBJS} ${BONUSES}
		ar rc ${NAME} ${OBJS} ${BONUSES}

${NAME}: ${OBJS}
		ar rc ${NAME} ${OBJS}

clean:
		rm -f ${OBJS} ${BONUSES}

fclean: clean
		rm -f ${NAME}

re: fclean all

.PHONY: all clean fclean re
